/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the ListGlobalIpProtocols200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListGlobalIpProtocols200Response{}

// ListGlobalIpProtocols200Response struct for ListGlobalIpProtocols200Response
type ListGlobalIpProtocols200Response struct {
	Data []GlobalIPProtocol `json:"data,omitempty"`
}

// NewListGlobalIpProtocols200Response instantiates a new ListGlobalIpProtocols200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListGlobalIpProtocols200Response() *ListGlobalIpProtocols200Response {
	this := ListGlobalIpProtocols200Response{}
	return &this
}

// NewListGlobalIpProtocols200ResponseWithDefaults instantiates a new ListGlobalIpProtocols200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListGlobalIpProtocols200ResponseWithDefaults() *ListGlobalIpProtocols200Response {
	this := ListGlobalIpProtocols200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListGlobalIpProtocols200Response) GetData() []GlobalIPProtocol {
	if o == nil || IsNil(o.Data) {
		var ret []GlobalIPProtocol
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGlobalIpProtocols200Response) GetDataOk() ([]GlobalIPProtocol, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListGlobalIpProtocols200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GlobalIPProtocol and assigns it to the Data field.
func (o *ListGlobalIpProtocols200Response) SetData(v []GlobalIPProtocol) {
	o.Data = v
}

func (o ListGlobalIpProtocols200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListGlobalIpProtocols200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableListGlobalIpProtocols200Response struct {
	value *ListGlobalIpProtocols200Response
	isSet bool
}

func (v NullableListGlobalIpProtocols200Response) Get() *ListGlobalIpProtocols200Response {
	return v.value
}

func (v *NullableListGlobalIpProtocols200Response) Set(val *ListGlobalIpProtocols200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListGlobalIpProtocols200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListGlobalIpProtocols200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListGlobalIpProtocols200Response(val *ListGlobalIpProtocols200Response) *NullableListGlobalIpProtocols200Response {
	return &NullableListGlobalIpProtocols200Response{value: val, isSet: true}
}

func (v NullableListGlobalIpProtocols200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListGlobalIpProtocols200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


