/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the ListDataUsageNotifications200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDataUsageNotifications200Response{}

// ListDataUsageNotifications200Response struct for ListDataUsageNotifications200Response
type ListDataUsageNotifications200Response struct {
	Data []SimCardDataUsageNotification `json:"data,omitempty"`
	Meta *PaginationMeta `json:"meta,omitempty"`
}

// NewListDataUsageNotifications200Response instantiates a new ListDataUsageNotifications200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDataUsageNotifications200Response() *ListDataUsageNotifications200Response {
	this := ListDataUsageNotifications200Response{}
	return &this
}

// NewListDataUsageNotifications200ResponseWithDefaults instantiates a new ListDataUsageNotifications200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDataUsageNotifications200ResponseWithDefaults() *ListDataUsageNotifications200Response {
	this := ListDataUsageNotifications200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListDataUsageNotifications200Response) GetData() []SimCardDataUsageNotification {
	if o == nil || IsNil(o.Data) {
		var ret []SimCardDataUsageNotification
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDataUsageNotifications200Response) GetDataOk() ([]SimCardDataUsageNotification, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListDataUsageNotifications200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []SimCardDataUsageNotification and assigns it to the Data field.
func (o *ListDataUsageNotifications200Response) SetData(v []SimCardDataUsageNotification) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ListDataUsageNotifications200Response) GetMeta() PaginationMeta {
	if o == nil || IsNil(o.Meta) {
		var ret PaginationMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDataUsageNotifications200Response) GetMetaOk() (*PaginationMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ListDataUsageNotifications200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given PaginationMeta and assigns it to the Meta field.
func (o *ListDataUsageNotifications200Response) SetMeta(v PaginationMeta) {
	o.Meta = &v
}

func (o ListDataUsageNotifications200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDataUsageNotifications200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableListDataUsageNotifications200Response struct {
	value *ListDataUsageNotifications200Response
	isSet bool
}

func (v NullableListDataUsageNotifications200Response) Get() *ListDataUsageNotifications200Response {
	return v.value
}

func (v *NullableListDataUsageNotifications200Response) Set(val *ListDataUsageNotifications200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListDataUsageNotifications200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListDataUsageNotifications200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDataUsageNotifications200Response(val *ListDataUsageNotifications200Response) *NullableListDataUsageNotifications200Response {
	return &NullableListDataUsageNotifications200Response{value: val, isSet: true}
}

func (v NullableListDataUsageNotifications200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDataUsageNotifications200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


