/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the NumberOrderResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NumberOrderResponse{}

// NumberOrderResponse struct for NumberOrderResponse
type NumberOrderResponse struct {
	Data *NumberOrderWithPhoneNumbers `json:"data,omitempty"`
}

// NewNumberOrderResponse instantiates a new NumberOrderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNumberOrderResponse() *NumberOrderResponse {
	this := NumberOrderResponse{}
	return &this
}

// NewNumberOrderResponseWithDefaults instantiates a new NumberOrderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNumberOrderResponseWithDefaults() *NumberOrderResponse {
	this := NumberOrderResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *NumberOrderResponse) GetData() NumberOrderWithPhoneNumbers {
	if o == nil || IsNil(o.Data) {
		var ret NumberOrderWithPhoneNumbers
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NumberOrderResponse) GetDataOk() (*NumberOrderWithPhoneNumbers, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *NumberOrderResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given NumberOrderWithPhoneNumbers and assigns it to the Data field.
func (o *NumberOrderResponse) SetData(v NumberOrderWithPhoneNumbers) {
	o.Data = &v
}

func (o NumberOrderResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NumberOrderResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableNumberOrderResponse struct {
	value *NumberOrderResponse
	isSet bool
}

func (v NullableNumberOrderResponse) Get() *NumberOrderResponse {
	return v.value
}

func (v *NullableNumberOrderResponse) Set(val *NumberOrderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNumberOrderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNumberOrderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNumberOrderResponse(val *NumberOrderResponse) *NullableNumberOrderResponse {
	return &NullableNumberOrderResponse{value: val, isSet: true}
}

func (v NullableNumberOrderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNumberOrderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


