/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the ListSimCardActions200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListSimCardActions200Response{}

// ListSimCardActions200Response struct for ListSimCardActions200Response
type ListSimCardActions200Response struct {
	Data []SIMCardAction `json:"data,omitempty"`
	Meta *PaginationMeta `json:"meta,omitempty"`
}

// NewListSimCardActions200Response instantiates a new ListSimCardActions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSimCardActions200Response() *ListSimCardActions200Response {
	this := ListSimCardActions200Response{}
	return &this
}

// NewListSimCardActions200ResponseWithDefaults instantiates a new ListSimCardActions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSimCardActions200ResponseWithDefaults() *ListSimCardActions200Response {
	this := ListSimCardActions200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListSimCardActions200Response) GetData() []SIMCardAction {
	if o == nil || IsNil(o.Data) {
		var ret []SIMCardAction
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSimCardActions200Response) GetDataOk() ([]SIMCardAction, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListSimCardActions200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []SIMCardAction and assigns it to the Data field.
func (o *ListSimCardActions200Response) SetData(v []SIMCardAction) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ListSimCardActions200Response) GetMeta() PaginationMeta {
	if o == nil || IsNil(o.Meta) {
		var ret PaginationMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSimCardActions200Response) GetMetaOk() (*PaginationMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ListSimCardActions200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given PaginationMeta and assigns it to the Meta field.
func (o *ListSimCardActions200Response) SetMeta(v PaginationMeta) {
	o.Meta = &v
}

func (o ListSimCardActions200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListSimCardActions200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableListSimCardActions200Response struct {
	value *ListSimCardActions200Response
	isSet bool
}

func (v NullableListSimCardActions200Response) Get() *ListSimCardActions200Response {
	return v.value
}

func (v *NullableListSimCardActions200Response) Set(val *ListSimCardActions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListSimCardActions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListSimCardActions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSimCardActions200Response(val *ListSimCardActions200Response) *NullableListSimCardActions200Response {
	return &NullableListSimCardActions200Response{value: val, isSet: true}
}

func (v NullableListSimCardActions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSimCardActions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


