/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the CallStreamingStartedEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CallStreamingStartedEvent{}

// CallStreamingStartedEvent struct for CallStreamingStartedEvent
type CallStreamingStartedEvent struct {
	Data *CallStreamingStarted `json:"data,omitempty"`
}

// NewCallStreamingStartedEvent instantiates a new CallStreamingStartedEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCallStreamingStartedEvent() *CallStreamingStartedEvent {
	this := CallStreamingStartedEvent{}
	return &this
}

// NewCallStreamingStartedEventWithDefaults instantiates a new CallStreamingStartedEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCallStreamingStartedEventWithDefaults() *CallStreamingStartedEvent {
	this := CallStreamingStartedEvent{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CallStreamingStartedEvent) GetData() CallStreamingStarted {
	if o == nil || IsNil(o.Data) {
		var ret CallStreamingStarted
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallStreamingStartedEvent) GetDataOk() (*CallStreamingStarted, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CallStreamingStartedEvent) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CallStreamingStarted and assigns it to the Data field.
func (o *CallStreamingStartedEvent) SetData(v CallStreamingStarted) {
	o.Data = &v
}

func (o CallStreamingStartedEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CallStreamingStartedEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCallStreamingStartedEvent struct {
	value *CallStreamingStartedEvent
	isSet bool
}

func (v NullableCallStreamingStartedEvent) Get() *CallStreamingStartedEvent {
	return v.value
}

func (v *NullableCallStreamingStartedEvent) Set(val *CallStreamingStartedEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableCallStreamingStartedEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableCallStreamingStartedEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCallStreamingStartedEvent(val *CallStreamingStartedEvent) *NullableCallStreamingStartedEvent {
	return &NullableCallStreamingStartedEvent{value: val, isSet: true}
}

func (v NullableCallStreamingStartedEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCallStreamingStartedEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


