/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the ConsumedData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsumedData{}

// ConsumedData Represents the amount of data consumed.
type ConsumedData struct {
	Unit *string `json:"unit,omitempty"`
	Amount *float64 `json:"amount,omitempty"`
}

// NewConsumedData instantiates a new ConsumedData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumedData() *ConsumedData {
	this := ConsumedData{}
	var unit string = "MB"
	this.Unit = &unit
	return &this
}

// NewConsumedDataWithDefaults instantiates a new ConsumedData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumedDataWithDefaults() *ConsumedData {
	this := ConsumedData{}
	var unit string = "MB"
	this.Unit = &unit
	return &this
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *ConsumedData) GetUnit() string {
	if o == nil || IsNil(o.Unit) {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumedData) GetUnitOk() (*string, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *ConsumedData) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *ConsumedData) SetUnit(v string) {
	o.Unit = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *ConsumedData) GetAmount() float64 {
	if o == nil || IsNil(o.Amount) {
		var ret float64
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumedData) GetAmountOk() (*float64, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *ConsumedData) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float64 and assigns it to the Amount field.
func (o *ConsumedData) SetAmount(v float64) {
	o.Amount = &v
}

func (o ConsumedData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsumedData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	return toSerialize, nil
}

type NullableConsumedData struct {
	value *ConsumedData
	isSet bool
}

func (v NullableConsumedData) Get() *ConsumedData {
	return v.value
}

func (v *NullableConsumedData) Set(val *ConsumedData) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumedData) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumedData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumedData(val *ConsumedData) *NullableConsumedData {
	return &NullableConsumedData{value: val, isSet: true}
}

func (v NullableConsumedData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumedData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


