/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the AutoRechargePref type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AutoRechargePref{}

// AutoRechargePref struct for AutoRechargePref
type AutoRechargePref struct {
	// The unique identifier for the auto recharge preference.
	Id *string `json:"id,omitempty"`
	// The record type.
	RecordType *string `json:"record_type,omitempty"`
	// The threshold amount at which the account will be recharged.
	ThresholdAmount *float64 `json:"threshold_amount,omitempty"`
	// The amount to recharge the account, the actual recharge amount will be the amount necessary to reach the threshold amount plus the recharge amount.
	RechargeAmount *float64 `json:"recharge_amount,omitempty"`
	// Whether auto recharge is enabled.
	Enabled *bool `json:"enabled,omitempty"`
	InvoiceEnabled *bool `json:"invoice_enabled,omitempty"`
	// The payment preference for auto recharge.
	Preference *string `json:"preference,omitempty"`
}

// NewAutoRechargePref instantiates a new AutoRechargePref object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutoRechargePref() *AutoRechargePref {
	this := AutoRechargePref{}
	return &this
}

// NewAutoRechargePrefWithDefaults instantiates a new AutoRechargePref object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutoRechargePrefWithDefaults() *AutoRechargePref {
	this := AutoRechargePref{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AutoRechargePref) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoRechargePref) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AutoRechargePref) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AutoRechargePref) SetId(v string) {
	o.Id = &v
}

// GetRecordType returns the RecordType field value if set, zero value otherwise.
func (o *AutoRechargePref) GetRecordType() string {
	if o == nil || IsNil(o.RecordType) {
		var ret string
		return ret
	}
	return *o.RecordType
}

// GetRecordTypeOk returns a tuple with the RecordType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoRechargePref) GetRecordTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RecordType) {
		return nil, false
	}
	return o.RecordType, true
}

// HasRecordType returns a boolean if a field has been set.
func (o *AutoRechargePref) HasRecordType() bool {
	if o != nil && !IsNil(o.RecordType) {
		return true
	}

	return false
}

// SetRecordType gets a reference to the given string and assigns it to the RecordType field.
func (o *AutoRechargePref) SetRecordType(v string) {
	o.RecordType = &v
}

// GetThresholdAmount returns the ThresholdAmount field value if set, zero value otherwise.
func (o *AutoRechargePref) GetThresholdAmount() float64 {
	if o == nil || IsNil(o.ThresholdAmount) {
		var ret float64
		return ret
	}
	return *o.ThresholdAmount
}

// GetThresholdAmountOk returns a tuple with the ThresholdAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoRechargePref) GetThresholdAmountOk() (*float64, bool) {
	if o == nil || IsNil(o.ThresholdAmount) {
		return nil, false
	}
	return o.ThresholdAmount, true
}

// HasThresholdAmount returns a boolean if a field has been set.
func (o *AutoRechargePref) HasThresholdAmount() bool {
	if o != nil && !IsNil(o.ThresholdAmount) {
		return true
	}

	return false
}

// SetThresholdAmount gets a reference to the given float64 and assigns it to the ThresholdAmount field.
func (o *AutoRechargePref) SetThresholdAmount(v float64) {
	o.ThresholdAmount = &v
}

// GetRechargeAmount returns the RechargeAmount field value if set, zero value otherwise.
func (o *AutoRechargePref) GetRechargeAmount() float64 {
	if o == nil || IsNil(o.RechargeAmount) {
		var ret float64
		return ret
	}
	return *o.RechargeAmount
}

// GetRechargeAmountOk returns a tuple with the RechargeAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoRechargePref) GetRechargeAmountOk() (*float64, bool) {
	if o == nil || IsNil(o.RechargeAmount) {
		return nil, false
	}
	return o.RechargeAmount, true
}

// HasRechargeAmount returns a boolean if a field has been set.
func (o *AutoRechargePref) HasRechargeAmount() bool {
	if o != nil && !IsNil(o.RechargeAmount) {
		return true
	}

	return false
}

// SetRechargeAmount gets a reference to the given float64 and assigns it to the RechargeAmount field.
func (o *AutoRechargePref) SetRechargeAmount(v float64) {
	o.RechargeAmount = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *AutoRechargePref) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoRechargePref) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *AutoRechargePref) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *AutoRechargePref) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetInvoiceEnabled returns the InvoiceEnabled field value if set, zero value otherwise.
func (o *AutoRechargePref) GetInvoiceEnabled() bool {
	if o == nil || IsNil(o.InvoiceEnabled) {
		var ret bool
		return ret
	}
	return *o.InvoiceEnabled
}

// GetInvoiceEnabledOk returns a tuple with the InvoiceEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoRechargePref) GetInvoiceEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.InvoiceEnabled) {
		return nil, false
	}
	return o.InvoiceEnabled, true
}

// HasInvoiceEnabled returns a boolean if a field has been set.
func (o *AutoRechargePref) HasInvoiceEnabled() bool {
	if o != nil && !IsNil(o.InvoiceEnabled) {
		return true
	}

	return false
}

// SetInvoiceEnabled gets a reference to the given bool and assigns it to the InvoiceEnabled field.
func (o *AutoRechargePref) SetInvoiceEnabled(v bool) {
	o.InvoiceEnabled = &v
}

// GetPreference returns the Preference field value if set, zero value otherwise.
func (o *AutoRechargePref) GetPreference() string {
	if o == nil || IsNil(o.Preference) {
		var ret string
		return ret
	}
	return *o.Preference
}

// GetPreferenceOk returns a tuple with the Preference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoRechargePref) GetPreferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Preference) {
		return nil, false
	}
	return o.Preference, true
}

// HasPreference returns a boolean if a field has been set.
func (o *AutoRechargePref) HasPreference() bool {
	if o != nil && !IsNil(o.Preference) {
		return true
	}

	return false
}

// SetPreference gets a reference to the given string and assigns it to the Preference field.
func (o *AutoRechargePref) SetPreference(v string) {
	o.Preference = &v
}

func (o AutoRechargePref) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AutoRechargePref) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.RecordType) {
		toSerialize["record_type"] = o.RecordType
	}
	if !IsNil(o.ThresholdAmount) {
		toSerialize["threshold_amount"] = o.ThresholdAmount
	}
	if !IsNil(o.RechargeAmount) {
		toSerialize["recharge_amount"] = o.RechargeAmount
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.InvoiceEnabled) {
		toSerialize["invoice_enabled"] = o.InvoiceEnabled
	}
	if !IsNil(o.Preference) {
		toSerialize["preference"] = o.Preference
	}
	return toSerialize, nil
}

type NullableAutoRechargePref struct {
	value *AutoRechargePref
	isSet bool
}

func (v NullableAutoRechargePref) Get() *AutoRechargePref {
	return v.value
}

func (v *NullableAutoRechargePref) Set(val *AutoRechargePref) {
	v.value = val
	v.isSet = true
}

func (v NullableAutoRechargePref) IsSet() bool {
	return v.isSet
}

func (v *NullableAutoRechargePref) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutoRechargePref(val *AutoRechargePref) *NullableAutoRechargePref {
	return &NullableAutoRechargePref{value: val, isSet: true}
}

func (v NullableAutoRechargePref) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutoRechargePref) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


