/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the CallControlCommandResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CallControlCommandResponse{}

// CallControlCommandResponse struct for CallControlCommandResponse
type CallControlCommandResponse struct {
	Data *CallControlCommandResult `json:"data,omitempty"`
}

// NewCallControlCommandResponse instantiates a new CallControlCommandResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCallControlCommandResponse() *CallControlCommandResponse {
	this := CallControlCommandResponse{}
	return &this
}

// NewCallControlCommandResponseWithDefaults instantiates a new CallControlCommandResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCallControlCommandResponseWithDefaults() *CallControlCommandResponse {
	this := CallControlCommandResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CallControlCommandResponse) GetData() CallControlCommandResult {
	if o == nil || IsNil(o.Data) {
		var ret CallControlCommandResult
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallControlCommandResponse) GetDataOk() (*CallControlCommandResult, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CallControlCommandResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CallControlCommandResult and assigns it to the Data field.
func (o *CallControlCommandResponse) SetData(v CallControlCommandResult) {
	o.Data = &v
}

func (o CallControlCommandResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CallControlCommandResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCallControlCommandResponse struct {
	value *CallControlCommandResponse
	isSet bool
}

func (v NullableCallControlCommandResponse) Get() *CallControlCommandResponse {
	return v.value
}

func (v *NullableCallControlCommandResponse) Set(val *CallControlCommandResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCallControlCommandResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCallControlCommandResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCallControlCommandResponse(val *CallControlCommandResponse) *NullableCallControlCommandResponse {
	return &NullableCallControlCommandResponse{value: val, isSet: true}
}

func (v NullableCallControlCommandResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCallControlCommandResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


