/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the ListPortingPhoneNumbers200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPortingPhoneNumbers200Response{}

// ListPortingPhoneNumbers200Response struct for ListPortingPhoneNumbers200Response
type ListPortingPhoneNumbers200Response struct {
	Data []PortingPhoneNumber `json:"data,omitempty"`
	Meta *PaginationMeta `json:"meta,omitempty"`
}

// NewListPortingPhoneNumbers200Response instantiates a new ListPortingPhoneNumbers200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPortingPhoneNumbers200Response() *ListPortingPhoneNumbers200Response {
	this := ListPortingPhoneNumbers200Response{}
	return &this
}

// NewListPortingPhoneNumbers200ResponseWithDefaults instantiates a new ListPortingPhoneNumbers200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPortingPhoneNumbers200ResponseWithDefaults() *ListPortingPhoneNumbers200Response {
	this := ListPortingPhoneNumbers200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListPortingPhoneNumbers200Response) GetData() []PortingPhoneNumber {
	if o == nil || IsNil(o.Data) {
		var ret []PortingPhoneNumber
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPortingPhoneNumbers200Response) GetDataOk() ([]PortingPhoneNumber, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListPortingPhoneNumbers200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []PortingPhoneNumber and assigns it to the Data field.
func (o *ListPortingPhoneNumbers200Response) SetData(v []PortingPhoneNumber) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ListPortingPhoneNumbers200Response) GetMeta() PaginationMeta {
	if o == nil || IsNil(o.Meta) {
		var ret PaginationMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPortingPhoneNumbers200Response) GetMetaOk() (*PaginationMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ListPortingPhoneNumbers200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given PaginationMeta and assigns it to the Meta field.
func (o *ListPortingPhoneNumbers200Response) SetMeta(v PaginationMeta) {
	o.Meta = &v
}

func (o ListPortingPhoneNumbers200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPortingPhoneNumbers200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableListPortingPhoneNumbers200Response struct {
	value *ListPortingPhoneNumbers200Response
	isSet bool
}

func (v NullableListPortingPhoneNumbers200Response) Get() *ListPortingPhoneNumbers200Response {
	return v.value
}

func (v *NullableListPortingPhoneNumbers200Response) Set(val *ListPortingPhoneNumbers200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListPortingPhoneNumbers200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListPortingPhoneNumbers200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPortingPhoneNumbers200Response(val *ListPortingPhoneNumbers200Response) *NullableListPortingPhoneNumbers200Response {
	return &NullableListPortingPhoneNumbers200Response{value: val, isSet: true}
}

func (v NullableListPortingPhoneNumbers200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPortingPhoneNumbers200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


