/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the TexmlCreateCallStreamingResponseBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TexmlCreateCallStreamingResponseBody{}

// TexmlCreateCallStreamingResponseBody struct for TexmlCreateCallStreamingResponseBody
type TexmlCreateCallStreamingResponseBody struct {
	AccountSid *string `json:"account_sid,omitempty"`
	CallSid *string `json:"call_sid,omitempty"`
	// Identifier of a resource.
	Sid *string `json:"sid,omitempty"`
	// The user specified name of Stream.
	Name *string `json:"name,omitempty"`
	// The status of the streaming.
	Status *string `json:"status,omitempty"`
	DateUpdated *string `json:"date_updated,omitempty"`
	// The relative URI for this streaming resource.
	Uri *string `json:"uri,omitempty"`
}

// NewTexmlCreateCallStreamingResponseBody instantiates a new TexmlCreateCallStreamingResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTexmlCreateCallStreamingResponseBody() *TexmlCreateCallStreamingResponseBody {
	this := TexmlCreateCallStreamingResponseBody{}
	return &this
}

// NewTexmlCreateCallStreamingResponseBodyWithDefaults instantiates a new TexmlCreateCallStreamingResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTexmlCreateCallStreamingResponseBodyWithDefaults() *TexmlCreateCallStreamingResponseBody {
	this := TexmlCreateCallStreamingResponseBody{}
	return &this
}

// GetAccountSid returns the AccountSid field value if set, zero value otherwise.
func (o *TexmlCreateCallStreamingResponseBody) GetAccountSid() string {
	if o == nil || IsNil(o.AccountSid) {
		var ret string
		return ret
	}
	return *o.AccountSid
}

// GetAccountSidOk returns a tuple with the AccountSid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TexmlCreateCallStreamingResponseBody) GetAccountSidOk() (*string, bool) {
	if o == nil || IsNil(o.AccountSid) {
		return nil, false
	}
	return o.AccountSid, true
}

// HasAccountSid returns a boolean if a field has been set.
func (o *TexmlCreateCallStreamingResponseBody) HasAccountSid() bool {
	if o != nil && !IsNil(o.AccountSid) {
		return true
	}

	return false
}

// SetAccountSid gets a reference to the given string and assigns it to the AccountSid field.
func (o *TexmlCreateCallStreamingResponseBody) SetAccountSid(v string) {
	o.AccountSid = &v
}

// GetCallSid returns the CallSid field value if set, zero value otherwise.
func (o *TexmlCreateCallStreamingResponseBody) GetCallSid() string {
	if o == nil || IsNil(o.CallSid) {
		var ret string
		return ret
	}
	return *o.CallSid
}

// GetCallSidOk returns a tuple with the CallSid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TexmlCreateCallStreamingResponseBody) GetCallSidOk() (*string, bool) {
	if o == nil || IsNil(o.CallSid) {
		return nil, false
	}
	return o.CallSid, true
}

// HasCallSid returns a boolean if a field has been set.
func (o *TexmlCreateCallStreamingResponseBody) HasCallSid() bool {
	if o != nil && !IsNil(o.CallSid) {
		return true
	}

	return false
}

// SetCallSid gets a reference to the given string and assigns it to the CallSid field.
func (o *TexmlCreateCallStreamingResponseBody) SetCallSid(v string) {
	o.CallSid = &v
}

// GetSid returns the Sid field value if set, zero value otherwise.
func (o *TexmlCreateCallStreamingResponseBody) GetSid() string {
	if o == nil || IsNil(o.Sid) {
		var ret string
		return ret
	}
	return *o.Sid
}

// GetSidOk returns a tuple with the Sid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TexmlCreateCallStreamingResponseBody) GetSidOk() (*string, bool) {
	if o == nil || IsNil(o.Sid) {
		return nil, false
	}
	return o.Sid, true
}

// HasSid returns a boolean if a field has been set.
func (o *TexmlCreateCallStreamingResponseBody) HasSid() bool {
	if o != nil && !IsNil(o.Sid) {
		return true
	}

	return false
}

// SetSid gets a reference to the given string and assigns it to the Sid field.
func (o *TexmlCreateCallStreamingResponseBody) SetSid(v string) {
	o.Sid = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TexmlCreateCallStreamingResponseBody) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TexmlCreateCallStreamingResponseBody) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TexmlCreateCallStreamingResponseBody) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TexmlCreateCallStreamingResponseBody) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TexmlCreateCallStreamingResponseBody) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TexmlCreateCallStreamingResponseBody) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TexmlCreateCallStreamingResponseBody) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *TexmlCreateCallStreamingResponseBody) SetStatus(v string) {
	o.Status = &v
}

// GetDateUpdated returns the DateUpdated field value if set, zero value otherwise.
func (o *TexmlCreateCallStreamingResponseBody) GetDateUpdated() string {
	if o == nil || IsNil(o.DateUpdated) {
		var ret string
		return ret
	}
	return *o.DateUpdated
}

// GetDateUpdatedOk returns a tuple with the DateUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TexmlCreateCallStreamingResponseBody) GetDateUpdatedOk() (*string, bool) {
	if o == nil || IsNil(o.DateUpdated) {
		return nil, false
	}
	return o.DateUpdated, true
}

// HasDateUpdated returns a boolean if a field has been set.
func (o *TexmlCreateCallStreamingResponseBody) HasDateUpdated() bool {
	if o != nil && !IsNil(o.DateUpdated) {
		return true
	}

	return false
}

// SetDateUpdated gets a reference to the given string and assigns it to the DateUpdated field.
func (o *TexmlCreateCallStreamingResponseBody) SetDateUpdated(v string) {
	o.DateUpdated = &v
}

// GetUri returns the Uri field value if set, zero value otherwise.
func (o *TexmlCreateCallStreamingResponseBody) GetUri() string {
	if o == nil || IsNil(o.Uri) {
		var ret string
		return ret
	}
	return *o.Uri
}

// GetUriOk returns a tuple with the Uri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TexmlCreateCallStreamingResponseBody) GetUriOk() (*string, bool) {
	if o == nil || IsNil(o.Uri) {
		return nil, false
	}
	return o.Uri, true
}

// HasUri returns a boolean if a field has been set.
func (o *TexmlCreateCallStreamingResponseBody) HasUri() bool {
	if o != nil && !IsNil(o.Uri) {
		return true
	}

	return false
}

// SetUri gets a reference to the given string and assigns it to the Uri field.
func (o *TexmlCreateCallStreamingResponseBody) SetUri(v string) {
	o.Uri = &v
}

func (o TexmlCreateCallStreamingResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TexmlCreateCallStreamingResponseBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountSid) {
		toSerialize["account_sid"] = o.AccountSid
	}
	if !IsNil(o.CallSid) {
		toSerialize["call_sid"] = o.CallSid
	}
	if !IsNil(o.Sid) {
		toSerialize["sid"] = o.Sid
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.DateUpdated) {
		toSerialize["date_updated"] = o.DateUpdated
	}
	if !IsNil(o.Uri) {
		toSerialize["uri"] = o.Uri
	}
	return toSerialize, nil
}

type NullableTexmlCreateCallStreamingResponseBody struct {
	value *TexmlCreateCallStreamingResponseBody
	isSet bool
}

func (v NullableTexmlCreateCallStreamingResponseBody) Get() *TexmlCreateCallStreamingResponseBody {
	return v.value
}

func (v *NullableTexmlCreateCallStreamingResponseBody) Set(val *TexmlCreateCallStreamingResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableTexmlCreateCallStreamingResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableTexmlCreateCallStreamingResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTexmlCreateCallStreamingResponseBody(val *TexmlCreateCallStreamingResponseBody) *NullableTexmlCreateCallStreamingResponseBody {
	return &NullableTexmlCreateCallStreamingResponseBody{value: val, isSet: true}
}

func (v NullableTexmlCreateCallStreamingResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTexmlCreateCallStreamingResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


