/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the ListCustomerServiceRecords403Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCustomerServiceRecords403Response{}

// ListCustomerServiceRecords403Response struct for ListCustomerServiceRecords403Response
type ListCustomerServiceRecords403Response struct {
	Errors []ForbiddenError `json:"errors,omitempty"`
}

// NewListCustomerServiceRecords403Response instantiates a new ListCustomerServiceRecords403Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCustomerServiceRecords403Response() *ListCustomerServiceRecords403Response {
	this := ListCustomerServiceRecords403Response{}
	return &this
}

// NewListCustomerServiceRecords403ResponseWithDefaults instantiates a new ListCustomerServiceRecords403Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCustomerServiceRecords403ResponseWithDefaults() *ListCustomerServiceRecords403Response {
	this := ListCustomerServiceRecords403Response{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ListCustomerServiceRecords403Response) GetErrors() []ForbiddenError {
	if o == nil || IsNil(o.Errors) {
		var ret []ForbiddenError
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCustomerServiceRecords403Response) GetErrorsOk() ([]ForbiddenError, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ListCustomerServiceRecords403Response) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []ForbiddenError and assigns it to the Errors field.
func (o *ListCustomerServiceRecords403Response) SetErrors(v []ForbiddenError) {
	o.Errors = v
}

func (o ListCustomerServiceRecords403Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCustomerServiceRecords403Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableListCustomerServiceRecords403Response struct {
	value *ListCustomerServiceRecords403Response
	isSet bool
}

func (v NullableListCustomerServiceRecords403Response) Get() *ListCustomerServiceRecords403Response {
	return v.value
}

func (v *NullableListCustomerServiceRecords403Response) Set(val *ListCustomerServiceRecords403Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListCustomerServiceRecords403Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListCustomerServiceRecords403Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCustomerServiceRecords403Response(val *ListCustomerServiceRecords403Response) *NullableListCustomerServiceRecords403Response {
	return &NullableListCustomerServiceRecords403Response{value: val, isSet: true}
}

func (v NullableListCustomerServiceRecords403Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCustomerServiceRecords403Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


