/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the NumberOrderBlockEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NumberOrderBlockEvent{}

// NumberOrderBlockEvent struct for NumberOrderBlockEvent
type NumberOrderBlockEvent struct {
	Data *NumberBlockOrder `json:"data,omitempty"`
}

// NewNumberOrderBlockEvent instantiates a new NumberOrderBlockEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNumberOrderBlockEvent() *NumberOrderBlockEvent {
	this := NumberOrderBlockEvent{}
	return &this
}

// NewNumberOrderBlockEventWithDefaults instantiates a new NumberOrderBlockEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNumberOrderBlockEventWithDefaults() *NumberOrderBlockEvent {
	this := NumberOrderBlockEvent{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *NumberOrderBlockEvent) GetData() NumberBlockOrder {
	if o == nil || IsNil(o.Data) {
		var ret NumberBlockOrder
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NumberOrderBlockEvent) GetDataOk() (*NumberBlockOrder, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *NumberOrderBlockEvent) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given NumberBlockOrder and assigns it to the Data field.
func (o *NumberOrderBlockEvent) SetData(v NumberBlockOrder) {
	o.Data = &v
}

func (o NumberOrderBlockEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NumberOrderBlockEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableNumberOrderBlockEvent struct {
	value *NumberOrderBlockEvent
	isSet bool
}

func (v NullableNumberOrderBlockEvent) Get() *NumberOrderBlockEvent {
	return v.value
}

func (v *NullableNumberOrderBlockEvent) Set(val *NumberOrderBlockEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableNumberOrderBlockEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableNumberOrderBlockEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNumberOrderBlockEvent(val *NumberOrderBlockEvent) *NullableNumberOrderBlockEvent {
	return &NullableNumberOrderBlockEvent{value: val, isSet: true}
}

func (v NullableNumberOrderBlockEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNumberOrderBlockEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


