/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the MetaResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetaResponse{}

// MetaResponse struct for MetaResponse
type MetaResponse struct {
	// This should likely be a URL to the relevant documentation
	Url *string `json:"url,omitempty"`
}

// NewMetaResponse instantiates a new MetaResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaResponse() *MetaResponse {
	this := MetaResponse{}
	return &this
}

// NewMetaResponseWithDefaults instantiates a new MetaResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaResponseWithDefaults() *MetaResponse {
	this := MetaResponse{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *MetaResponse) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaResponse) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *MetaResponse) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *MetaResponse) SetUrl(v string) {
	o.Url = &v
}

func (o MetaResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetaResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableMetaResponse struct {
	value *MetaResponse
	isSet bool
}

func (v NullableMetaResponse) Get() *MetaResponse {
	return v.value
}

func (v *NullableMetaResponse) Set(val *MetaResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaResponse(val *MetaResponse) *NullableMetaResponse {
	return &NullableMetaResponse{value: val, isSet: true}
}

func (v NullableMetaResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


