/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the CreateMigration200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateMigration200Response{}

// CreateMigration200Response struct for CreateMigration200Response
type CreateMigration200Response struct {
	Data *MigrationParams `json:"data,omitempty"`
}

// NewCreateMigration200Response instantiates a new CreateMigration200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMigration200Response() *CreateMigration200Response {
	this := CreateMigration200Response{}
	return &this
}

// NewCreateMigration200ResponseWithDefaults instantiates a new CreateMigration200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMigration200ResponseWithDefaults() *CreateMigration200Response {
	this := CreateMigration200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateMigration200Response) GetData() MigrationParams {
	if o == nil || IsNil(o.Data) {
		var ret MigrationParams
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMigration200Response) GetDataOk() (*MigrationParams, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateMigration200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given MigrationParams and assigns it to the Data field.
func (o *CreateMigration200Response) SetData(v MigrationParams) {
	o.Data = &v
}

func (o CreateMigration200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateMigration200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreateMigration200Response struct {
	value *CreateMigration200Response
	isSet bool
}

func (v NullableCreateMigration200Response) Get() *CreateMigration200Response {
	return v.value
}

func (v *NullableCreateMigration200Response) Set(val *CreateMigration200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMigration200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMigration200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMigration200Response(val *CreateMigration200Response) *NullableCreateMigration200Response {
	return &NullableCreateMigration200Response{value: val, isSet: true}
}

func (v NullableCreateMigration200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMigration200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


