/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the ListNumberReservationsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListNumberReservationsResponse{}

// ListNumberReservationsResponse struct for ListNumberReservationsResponse
type ListNumberReservationsResponse struct {
	Data []NumberReservation `json:"data,omitempty"`
	Meta *PaginationMeta `json:"meta,omitempty"`
}

// NewListNumberReservationsResponse instantiates a new ListNumberReservationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListNumberReservationsResponse() *ListNumberReservationsResponse {
	this := ListNumberReservationsResponse{}
	return &this
}

// NewListNumberReservationsResponseWithDefaults instantiates a new ListNumberReservationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListNumberReservationsResponseWithDefaults() *ListNumberReservationsResponse {
	this := ListNumberReservationsResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListNumberReservationsResponse) GetData() []NumberReservation {
	if o == nil || IsNil(o.Data) {
		var ret []NumberReservation
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListNumberReservationsResponse) GetDataOk() ([]NumberReservation, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListNumberReservationsResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []NumberReservation and assigns it to the Data field.
func (o *ListNumberReservationsResponse) SetData(v []NumberReservation) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ListNumberReservationsResponse) GetMeta() PaginationMeta {
	if o == nil || IsNil(o.Meta) {
		var ret PaginationMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListNumberReservationsResponse) GetMetaOk() (*PaginationMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ListNumberReservationsResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given PaginationMeta and assigns it to the Meta field.
func (o *ListNumberReservationsResponse) SetMeta(v PaginationMeta) {
	o.Meta = &v
}

func (o ListNumberReservationsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListNumberReservationsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableListNumberReservationsResponse struct {
	value *ListNumberReservationsResponse
	isSet bool
}

func (v NullableListNumberReservationsResponse) Get() *ListNumberReservationsResponse {
	return v.value
}

func (v *NullableListNumberReservationsResponse) Set(val *ListNumberReservationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListNumberReservationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListNumberReservationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListNumberReservationsResponse(val *ListNumberReservationsResponse) *NullableListNumberReservationsResponse {
	return &NullableListNumberReservationsResponse{value: val, isSet: true}
}

func (v NullableListNumberReservationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListNumberReservationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


