/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the PortingPhoneNumberBlockPhoneNumberRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PortingPhoneNumberBlockPhoneNumberRange{}

// PortingPhoneNumberBlockPhoneNumberRange Specifies the phone number range for this porting phone number block.
type PortingPhoneNumberBlockPhoneNumberRange struct {
	// Specifies the start of the phone number range for this porting phone number block.
	StartAt *string `json:"start_at,omitempty" validate:"regexp=^\\\\+\\\\d{7,15}$"`
	// Specifies the end of the phone number range for this porting phone number block.
	EndAt *string `json:"end_at,omitempty" validate:"regexp=^\\\\+\\\\d{7,15}$"`
}

// NewPortingPhoneNumberBlockPhoneNumberRange instantiates a new PortingPhoneNumberBlockPhoneNumberRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPortingPhoneNumberBlockPhoneNumberRange() *PortingPhoneNumberBlockPhoneNumberRange {
	this := PortingPhoneNumberBlockPhoneNumberRange{}
	return &this
}

// NewPortingPhoneNumberBlockPhoneNumberRangeWithDefaults instantiates a new PortingPhoneNumberBlockPhoneNumberRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPortingPhoneNumberBlockPhoneNumberRangeWithDefaults() *PortingPhoneNumberBlockPhoneNumberRange {
	this := PortingPhoneNumberBlockPhoneNumberRange{}
	return &this
}

// GetStartAt returns the StartAt field value if set, zero value otherwise.
func (o *PortingPhoneNumberBlockPhoneNumberRange) GetStartAt() string {
	if o == nil || IsNil(o.StartAt) {
		var ret string
		return ret
	}
	return *o.StartAt
}

// GetStartAtOk returns a tuple with the StartAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortingPhoneNumberBlockPhoneNumberRange) GetStartAtOk() (*string, bool) {
	if o == nil || IsNil(o.StartAt) {
		return nil, false
	}
	return o.StartAt, true
}

// HasStartAt returns a boolean if a field has been set.
func (o *PortingPhoneNumberBlockPhoneNumberRange) HasStartAt() bool {
	if o != nil && !IsNil(o.StartAt) {
		return true
	}

	return false
}

// SetStartAt gets a reference to the given string and assigns it to the StartAt field.
func (o *PortingPhoneNumberBlockPhoneNumberRange) SetStartAt(v string) {
	o.StartAt = &v
}

// GetEndAt returns the EndAt field value if set, zero value otherwise.
func (o *PortingPhoneNumberBlockPhoneNumberRange) GetEndAt() string {
	if o == nil || IsNil(o.EndAt) {
		var ret string
		return ret
	}
	return *o.EndAt
}

// GetEndAtOk returns a tuple with the EndAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortingPhoneNumberBlockPhoneNumberRange) GetEndAtOk() (*string, bool) {
	if o == nil || IsNil(o.EndAt) {
		return nil, false
	}
	return o.EndAt, true
}

// HasEndAt returns a boolean if a field has been set.
func (o *PortingPhoneNumberBlockPhoneNumberRange) HasEndAt() bool {
	if o != nil && !IsNil(o.EndAt) {
		return true
	}

	return false
}

// SetEndAt gets a reference to the given string and assigns it to the EndAt field.
func (o *PortingPhoneNumberBlockPhoneNumberRange) SetEndAt(v string) {
	o.EndAt = &v
}

func (o PortingPhoneNumberBlockPhoneNumberRange) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PortingPhoneNumberBlockPhoneNumberRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StartAt) {
		toSerialize["start_at"] = o.StartAt
	}
	if !IsNil(o.EndAt) {
		toSerialize["end_at"] = o.EndAt
	}
	return toSerialize, nil
}

type NullablePortingPhoneNumberBlockPhoneNumberRange struct {
	value *PortingPhoneNumberBlockPhoneNumberRange
	isSet bool
}

func (v NullablePortingPhoneNumberBlockPhoneNumberRange) Get() *PortingPhoneNumberBlockPhoneNumberRange {
	return v.value
}

func (v *NullablePortingPhoneNumberBlockPhoneNumberRange) Set(val *PortingPhoneNumberBlockPhoneNumberRange) {
	v.value = val
	v.isSet = true
}

func (v NullablePortingPhoneNumberBlockPhoneNumberRange) IsSet() bool {
	return v.isSet
}

func (v *NullablePortingPhoneNumberBlockPhoneNumberRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePortingPhoneNumberBlockPhoneNumberRange(val *PortingPhoneNumberBlockPhoneNumberRange) *NullablePortingPhoneNumberBlockPhoneNumberRange {
	return &NullablePortingPhoneNumberBlockPhoneNumberRange{value: val, isSet: true}
}

func (v NullablePortingPhoneNumberBlockPhoneNumberRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePortingPhoneNumberBlockPhoneNumberRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


