/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProfileAssignmentPhoneNumbers type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileAssignmentPhoneNumbers{}

// ProfileAssignmentPhoneNumbers struct for ProfileAssignmentPhoneNumbers
type ProfileAssignmentPhoneNumbers struct {
	// The ID of the task associated with the phone number.
	TaskId string `json:"taskId"`
	// The phone number that the status is being checked for.
	PhoneNumber string `json:"phoneNumber"`
	// The status of the associated phone number assignment.
	Status string `json:"status"`
}

type _ProfileAssignmentPhoneNumbers ProfileAssignmentPhoneNumbers

// NewProfileAssignmentPhoneNumbers instantiates a new ProfileAssignmentPhoneNumbers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileAssignmentPhoneNumbers(taskId string, phoneNumber string, status string) *ProfileAssignmentPhoneNumbers {
	this := ProfileAssignmentPhoneNumbers{}
	this.TaskId = taskId
	this.PhoneNumber = phoneNumber
	this.Status = status
	return &this
}

// NewProfileAssignmentPhoneNumbersWithDefaults instantiates a new ProfileAssignmentPhoneNumbers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileAssignmentPhoneNumbersWithDefaults() *ProfileAssignmentPhoneNumbers {
	this := ProfileAssignmentPhoneNumbers{}
	return &this
}

// GetTaskId returns the TaskId field value
func (o *ProfileAssignmentPhoneNumbers) GetTaskId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value
// and a boolean to check if the value has been set.
func (o *ProfileAssignmentPhoneNumbers) GetTaskIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskId, true
}

// SetTaskId sets field value
func (o *ProfileAssignmentPhoneNumbers) SetTaskId(v string) {
	o.TaskId = v
}

// GetPhoneNumber returns the PhoneNumber field value
func (o *ProfileAssignmentPhoneNumbers) GetPhoneNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value
// and a boolean to check if the value has been set.
func (o *ProfileAssignmentPhoneNumbers) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneNumber, true
}

// SetPhoneNumber sets field value
func (o *ProfileAssignmentPhoneNumbers) SetPhoneNumber(v string) {
	o.PhoneNumber = v
}

// GetStatus returns the Status field value
func (o *ProfileAssignmentPhoneNumbers) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ProfileAssignmentPhoneNumbers) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ProfileAssignmentPhoneNumbers) SetStatus(v string) {
	o.Status = v
}

func (o ProfileAssignmentPhoneNumbers) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileAssignmentPhoneNumbers) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["taskId"] = o.TaskId
	toSerialize["phoneNumber"] = o.PhoneNumber
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *ProfileAssignmentPhoneNumbers) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"taskId",
		"phoneNumber",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProfileAssignmentPhoneNumbers := _ProfileAssignmentPhoneNumbers{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProfileAssignmentPhoneNumbers)

	if err != nil {
		return err
	}

	*o = ProfileAssignmentPhoneNumbers(varProfileAssignmentPhoneNumbers)

	return err
}

type NullableProfileAssignmentPhoneNumbers struct {
	value *ProfileAssignmentPhoneNumbers
	isSet bool
}

func (v NullableProfileAssignmentPhoneNumbers) Get() *ProfileAssignmentPhoneNumbers {
	return v.value
}

func (v *NullableProfileAssignmentPhoneNumbers) Set(val *ProfileAssignmentPhoneNumbers) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileAssignmentPhoneNumbers) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileAssignmentPhoneNumbers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileAssignmentPhoneNumbers(val *ProfileAssignmentPhoneNumbers) *NullableProfileAssignmentPhoneNumbers {
	return &NullableProfileAssignmentPhoneNumbers{value: val, isSet: true}
}

func (v NullableProfileAssignmentPhoneNumbers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileAssignmentPhoneNumbers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


