/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
)

// checks if the VerifyProfileMessageTemplateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyProfileMessageTemplateResponse{}

// VerifyProfileMessageTemplateResponse struct for VerifyProfileMessageTemplateResponse
type VerifyProfileMessageTemplateResponse struct {
	Id *string `json:"id,omitempty"`
	Text *string `json:"text,omitempty"`
}

// NewVerifyProfileMessageTemplateResponse instantiates a new VerifyProfileMessageTemplateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyProfileMessageTemplateResponse() *VerifyProfileMessageTemplateResponse {
	this := VerifyProfileMessageTemplateResponse{}
	return &this
}

// NewVerifyProfileMessageTemplateResponseWithDefaults instantiates a new VerifyProfileMessageTemplateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyProfileMessageTemplateResponseWithDefaults() *VerifyProfileMessageTemplateResponse {
	this := VerifyProfileMessageTemplateResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *VerifyProfileMessageTemplateResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyProfileMessageTemplateResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *VerifyProfileMessageTemplateResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *VerifyProfileMessageTemplateResponse) SetId(v string) {
	o.Id = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *VerifyProfileMessageTemplateResponse) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyProfileMessageTemplateResponse) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *VerifyProfileMessageTemplateResponse) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *VerifyProfileMessageTemplateResponse) SetText(v string) {
	o.Text = &v
}

func (o VerifyProfileMessageTemplateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyProfileMessageTemplateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	return toSerialize, nil
}

type NullableVerifyProfileMessageTemplateResponse struct {
	value *VerifyProfileMessageTemplateResponse
	isSet bool
}

func (v NullableVerifyProfileMessageTemplateResponse) Get() *VerifyProfileMessageTemplateResponse {
	return v.value
}

func (v *NullableVerifyProfileMessageTemplateResponse) Set(val *VerifyProfileMessageTemplateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyProfileMessageTemplateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyProfileMessageTemplateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyProfileMessageTemplateResponse(val *VerifyProfileMessageTemplateResponse) *NullableVerifyProfileMessageTemplateResponse {
	return &NullableVerifyProfileMessageTemplateResponse{value: val, isSet: true}
}

func (v NullableVerifyProfileMessageTemplateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyProfileMessageTemplateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


