/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
	"fmt"
)


// ScheduledEventResponse Union type for different scheduled event response types
type ScheduledEventResponse struct {
	ScheduledPhoneCallEventResponse *ScheduledPhoneCallEventResponse
	ScheduledSmsEventResponse *ScheduledSmsEventResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ScheduledEventResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ScheduledPhoneCallEventResponse
	err = json.Unmarshal(data, &dst.ScheduledPhoneCallEventResponse);
	if err == nil {
		jsonScheduledPhoneCallEventResponse, _ := json.Marshal(dst.ScheduledPhoneCallEventResponse)
		if string(jsonScheduledPhoneCallEventResponse) == "{}" { // empty struct
			dst.ScheduledPhoneCallEventResponse = nil
		} else {
			return nil // data stored in dst.ScheduledPhoneCallEventResponse, return on the first match
		}
	} else {
		dst.ScheduledPhoneCallEventResponse = nil
	}

	// try to unmarshal JSON data into ScheduledSmsEventResponse
	err = json.Unmarshal(data, &dst.ScheduledSmsEventResponse);
	if err == nil {
		jsonScheduledSmsEventResponse, _ := json.Marshal(dst.ScheduledSmsEventResponse)
		if string(jsonScheduledSmsEventResponse) == "{}" { // empty struct
			dst.ScheduledSmsEventResponse = nil
		} else {
			return nil // data stored in dst.ScheduledSmsEventResponse, return on the first match
		}
	} else {
		dst.ScheduledSmsEventResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ScheduledEventResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ScheduledEventResponse) MarshalJSON() ([]byte, error) {
	if src.ScheduledPhoneCallEventResponse != nil {
		return json.Marshal(&src.ScheduledPhoneCallEventResponse)
	}

	if src.ScheduledSmsEventResponse != nil {
		return json.Marshal(&src.ScheduledSmsEventResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableScheduledEventResponse struct {
	value *ScheduledEventResponse
	isSet bool
}

func (v NullableScheduledEventResponse) Get() *ScheduledEventResponse {
	return v.value
}

func (v *NullableScheduledEventResponse) Set(val *ScheduledEventResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduledEventResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduledEventResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduledEventResponse(val *ScheduledEventResponse) *NullableScheduledEventResponse {
	return &NullableScheduledEventResponse{value: val, isSet: true}
}

func (v NullableScheduledEventResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduledEventResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


