/*
Telnyx API

SIP trunking, SMS, MMS, Call Control and Telephony Data Services.

API version: 2.0.0
Contact: support@telnyx.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package telnyx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerificationCodesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerificationCodesRequest{}

// VerificationCodesRequest struct for VerificationCodesRequest
type VerificationCodesRequest struct {
	PhoneNumbers []string `json:"phone_numbers"`
	VerificationMethod string `json:"verification_method"`
}

type _VerificationCodesRequest VerificationCodesRequest

// NewVerificationCodesRequest instantiates a new VerificationCodesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerificationCodesRequest(phoneNumbers []string, verificationMethod string) *VerificationCodesRequest {
	this := VerificationCodesRequest{}
	this.PhoneNumbers = phoneNumbers
	this.VerificationMethod = verificationMethod
	return &this
}

// NewVerificationCodesRequestWithDefaults instantiates a new VerificationCodesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerificationCodesRequestWithDefaults() *VerificationCodesRequest {
	this := VerificationCodesRequest{}
	return &this
}

// GetPhoneNumbers returns the PhoneNumbers field value
func (o *VerificationCodesRequest) GetPhoneNumbers() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.PhoneNumbers
}

// GetPhoneNumbersOk returns a tuple with the PhoneNumbers field value
// and a boolean to check if the value has been set.
func (o *VerificationCodesRequest) GetPhoneNumbersOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneNumbers, true
}

// SetPhoneNumbers sets field value
func (o *VerificationCodesRequest) SetPhoneNumbers(v []string) {
	o.PhoneNumbers = v
}

// GetVerificationMethod returns the VerificationMethod field value
func (o *VerificationCodesRequest) GetVerificationMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerificationMethod
}

// GetVerificationMethodOk returns a tuple with the VerificationMethod field value
// and a boolean to check if the value has been set.
func (o *VerificationCodesRequest) GetVerificationMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerificationMethod, true
}

// SetVerificationMethod sets field value
func (o *VerificationCodesRequest) SetVerificationMethod(v string) {
	o.VerificationMethod = v
}

func (o VerificationCodesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerificationCodesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phone_numbers"] = o.PhoneNumbers
	toSerialize["verification_method"] = o.VerificationMethod
	return toSerialize, nil
}

func (o *VerificationCodesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phone_numbers",
		"verification_method",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerificationCodesRequest := _VerificationCodesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerificationCodesRequest)

	if err != nil {
		return err
	}

	*o = VerificationCodesRequest(varVerificationCodesRequest)

	return err
}

type NullableVerificationCodesRequest struct {
	value *VerificationCodesRequest
	isSet bool
}

func (v NullableVerificationCodesRequest) Get() *VerificationCodesRequest {
	return v.value
}

func (v *NullableVerificationCodesRequest) Set(val *VerificationCodesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVerificationCodesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVerificationCodesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerificationCodesRequest(val *VerificationCodesRequest) *NullableVerificationCodesRequest {
	return &NullableVerificationCodesRequest{value: val, isSet: true}
}

func (v NullableVerificationCodesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerificationCodesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


